################## 계정, 인증 관리 #####################

### 전체 계정 조회
GET {{Local}}/api/admin/account
accept: application/json
Authorization: {{Authorization}}
X-RCS-Brandkey: BK.lSrB2204NfIdsY4

### 새로운 계정 추가
POST {{Local}}/api/admin/account
accept: application/json
Authorization: {{Authorization}}
Content-Type: application/json

{
       "id": "nanumi",
       "pwd": "park",
       "svcNm": "Tester",
       "roleCd": "USER"
}

### 토큰 발급
POST {{Local}}/api/auth/login
Content-Type: application/json

{
    "username": "nanumi",
    "password": "nanumi"
}

### 토큰 재발급
GET {{Local}}/api/auth/token
Content-Type: application/json
Authorization: {{Authorization}}




################## 대역 관리 #####################

### 전체 대역 번호 조회
GET {{Local}}/api/band
accept: application/json
Authorization: {{Authorization}}

###
POST {{Local}}/api/band
Content-Type: application/json
Authorization: {{Authorization}}

{

}

###
PUT {{Local}}/api/band
Content-Type: application/json
Authorization: {{Authorization}}

{

}

###
DELETE {{Local}}/api/band
Content-Type: application/json
Authorization: {{Authorization}}

{

}

### SerialNo 조회
GET {{Local}}/api/band/82-0303-3450
Content-Type: application/json
Authorization: {{Authorization}}


### categiry 조회
GET {{Local}}/api/band/category/FAX
Content-Type: application/json
Authorization: {{Authorization}}




################## 수신 번호 관리 #####################

### 전체 수신 번호 조회
GET {{Local}}/api/receptions
accept: application/json
Authorization: {{Authorization}}
