################## 계정, 인증 관리 #####################

### 전체 계정 조회
GET {{Local}}/api/admin/account
accept: application/json
Authorization: {{AccessToken}}
X-RCS-Brandkey: BK.lSrB2204NfIdsY4

### 새로운 계정 추가
POST {{Local}}/api/admin/account
accept: application/json
Authorization: {{AccessToken}}
Content-Type: application/json

{
       "id": "nanumi",
       "pwd": "park",
       "svcNm": "Tester",
       "roleCd": "USER"
}

### 토큰 발급
POST {{Local}}/api/auth/login
Content-Type: application/json

{
    "username": "nanumi",
    "password": "nanumi"
}

### 토큰 재발급
GET {{Local}}/api/auth/token
Content-Type: application/json
Authorization: {{RefreshToken}}




################## 대역 관리 #####################

### 전체 대역 번호 조회
GET {{Local}}/api/band
accept: application/json
Authorization: {{AccessToken}}


### 신규 대역  입력
POST {{Local}}/api/band
Content-Type: application/json
Authorization: {{AccessToken}}

{
  "serialNo":"82-0303-3450",
  "countryNo":"82",
  "localNo":"0303",
  "baseNo":"3450",
  "startNo":"0000",
  "endNo":"5000",
  "category":"FAX"
}

### 대역 업데이트
PUT {{Local}}/api/band/82-0303-3449
accept: application/json
Content-Type: application/json
Authorization: {{AccessToken}}

{
  "serialNo":"82-0303-3450",
  "startNo":"0000",
  "endNo":"4000",
  "category":"FAX",
  "status": 0
}

###
DELETE {{Local}}/api/band
Content-Type: application/json
Authorization: {{AccessToken}}

{

}


### SerialNo 조회
GET {{Local}}/api/band/82-0303-3450
Content-Type: application/json
Authorization: {{AccessToken}}


### categiry 조회
GET {{Local}}/api/band/category/MO
Content-Type: application/json
Authorization: {{AccessToken}}


#############할당 대역 관리#############

### 할당 대역 조회(계정)
GET {{Local}}/api/assignments
Content-Type: application/json
Authorization: {{AccessToken}}


###
POST {{Local}}/api/assignments
Content-Type: application/json
Authorization: {{AccessToken}}

{
  "serialNo":"82-0303-3440",
  "startNo":"4000",
  "endNo":"5000",
  "svcId":"nanumi"
}


###
PUT {{Local}}/api/assignments
Content-Type: application/json
Authorization: {{AccessToken}}

{
  "serialNo":"82-0303-3440",
  "startNo":"0000",
  "endNo":"8000",
  "status":"0",
  "svcId":"nanumi"
}

################## 수신 번호 관리 #####################

### 전체 수신 번호 조회
GET {{Local}}/api/receptions
accept: application/json
Authorization: {{AccessToken}}
